// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpLint")>]
[<assembly: AssemblyProductAttribute("FSharpLint")>]
[<assembly: AssemblyDescriptionAttribute("Lint tool for F#.")>]
[<assembly: AssemblyVersionAttribute("0.7.1")>]
[<assembly: AssemblyFileVersionAttribute("0.7.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpLint"
    let [<Literal>] AssemblyProduct = "FSharpLint"
    let [<Literal>] AssemblyDescription = "Lint tool for F#."
    let [<Literal>] AssemblyVersion = "0.7.1"
    let [<Literal>] AssemblyFileVersion = "0.7.1"
